disabled_rules:
  # - block_based_kvo # rxswift
  - file_length
  - function_body_length
  - notification_center_detachment
  - todo
  - trailing_whitespace
  - unused_optional_binding
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains # rxswift
  - multiline_parameters
  - nimble_operator # nimble
  - no_extension_access_modifier
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  # - quick_discouraged_call
  # - quick_discouraged_focused_test
  # - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_nil_coalescing
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
excluded:
  - Carthage
  - Pods


identifier_name:
  min_length: 3
  max_length:
    warning: 30
  excluded:
    - id
    - i
    - j
    - k
large_tuple: 4
line_length: 150
trailing_comma:
  mandatory_comma: false